# Book settings
title: Introduction to Probabilistic Machine Learning
author: C. Bogoclu, N. Friedlich & R. Vosshall
logo: logo.png
exclude_patterns: ["README.md", "probML/BayesianNN.md"]

latex:
  latex_documents:
    targetname: AML.tex

bibtex_bibfiles:
  - references.bib

html:
  favicon                   : "favicon.ico"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  extra_navbar              : Powered by <a href="https://jupyterbook.org/"><img alt="Jupyter Book" src="https://jupyterbook.org/badge.svg" width="100"></a>
  extra_footer              : Content on this site is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">a CC BY-NC-NB 4.0 licence</a>.
  baseurl                   : "https://probabilistic-ml.github.io/lecture-notes/welcome.html"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/


# Information about where the book exists on the web
repository:
  url                       : https://github.com/Probabilistic-ML/lecture-notes  # Online location of your book
  path_to_book              : ProbabilisticML

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url             : "" 
  # "https://mybinder.org"
  # thebe                     : true

sphinx:
  extra_extensions:
   - sphinx.ext.intersphinx
  config:
    html_show_copyright: false
    language: en
    # bibtex_reference_style: author_year # label
    latex_toplevel_sectioning: 'part'
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    intersphinx_mapping:
      Python 3: ['https://docs.python.org/3/', null]
      tensorflow: ['https://www.tensorflow.org/api_docs/python', 'https://github.com/mr-ubik/tensorflow-intersphinx/raw/master/tf2_py_objects.inv']
      matplotlib [stable]: ['https://matplotlib.org/stable/', null]
      numpy [stable]: ['https://numpy.org/doc/stable/', null]
      pandas [latest?]: ['https://pandas.pydata.org/docs/', null]
      scikit-learn [stable]: ['https://scikit-learn.org/stable/', null]
      scipy [latest]: ['https://docs.scipy.org/doc/scipy/reference/', null]
      jax [latest]: ['https://jax.readthedocs.io/en/latest/', null]
      seaborn [stable]: ['https://seaborn.pydata.org/', null]


execute:
  timeout: -1
  execute_notebooks: force # "off", cache
  exclude_patterns:
    - "02_probML/02_GPforML/09_examples.ipynb" # execution takes too long

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_image
