name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    # For equation rendering in plots
    - name: Install TeXlive 
      run: |
        sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super dvipng

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./ProbabilisticML

    # Push jupyter cache
    - name: Update cache
      run: |
        git config --global user.name 'rvosshall'
        git config --global user.email 'rvosshall@users.noreply.github.com'
        git add .
        git commit -m "cache update"
        git push

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ProbabilisticML/_build/html
